### ISSUE TITLE
Discourse is down

### ISSUE THREAD

**Issue by HLFH** [PTCE-Public/popcorn-desktop#6]
Discourse is down. Please fix it.

https://discuss.popcorntimece.tk/

Thanks,

**Comment by MrUltimate** [comment]
*Discuss

**Comment by HLFH** [comment]
It's powered by Discourse software. discuss.popcorntimece.tk is only the URL.

**Comment by MrUltimate** [comment]
Ah. Ok.

**Comment by MrUltimate** [comment]
Look at this: https://github.com/PTCE-Public/popcorn-desktop/issues/2

**Comment by HLFH** [comment]
When they say "discuss", they are talking about their Discourse instance powered by a Docker container. https://github.com/discourse/discourse

**Comment by Breaking1** [comment]
They have created a new one, you can find it here:

https://discuss.popcorntimece.ch/

**Comment by HLFH** [comment]
I moved to popcorntime.sh. Solved for me. Solved for you too in a green manner, apparently. 
<img width="817" alt="popcorn time" src="https://cloud.githubusercontent.com/assets/2359059/13380161/5d54388c-de3c-11e5-9e2a-a4ac8a372567.png">
